#109 Add color picker when create new calendar
OpenPaaS-Suite/esn-frontend-calendar pull request #131
Opened 2020-09-24 05:00 UTC by pbson

![color2](https://user-images.githubusercontent.com/32195667/94102892-62218900-fe5d-11ea-9870-8e10b4b2a855.gif)

2020-09-24 06:34 UTC, tuanlc commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.js
> +        }
```suggestion
        self.color = self.selected in self.CAL_LIST_OF_COLORS ? self.CAL_LIST_OF_COLORS[self.selected] : self.selected;
```

2020-09-24 06:34 UTC, tuanlc commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +    border: 2px dashed #B5B5B5;
```suggestion
   .all-centered;

    margin: 3px;
    border: 2px dashed #B5B5B5;
```

2020-09-24 06:35 UTC, tuanlc commented
LGTM!

2020-09-24 06:35 UTC, huy-ta commented
I think we can add some auto-contrast (CSS) mechanism to the "+" mark so that when the user chooses a bright color, the "+" will still be easily seen.

2020-09-25 08:16 UTC, pbson commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.js
> +        }
FIXED

2020-09-25 08:16 UTC, pbson commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +    border: 2px dashed #B5B5B5;
FIXED

2020-09-25 08:18 UTC, huy-ta commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +  }
Will these pollute `input[type="color"]` everywhere? Shouldn't you put it in some local CSS scope?

2020-09-25 08:19 UTC, huy-ta commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.pug
> +            ng-init = "colorValue = color",
```suggestion
            type="color",
            ng-model="colorValue",
            ng-change="select(colorValue)",
            ng-init="colorValue = color"
```

2020-09-25 08:23 UTC, huy-ta commented
LGTM, make sure you do these things though:

- [ ] Write tests for the changes
- [ ] Test it in our supported browsers (Firefox, Chrome, Safari)
- [ ] Test it in mobile devices

2020-09-28 03:27 UTC, pbson commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.pug
> +            ng-init = "colorValue = color",
FIXED

2020-09-28 03:54 UTC, huy-ta approved these changes

2020-09-28 03:54 UTC, huy-ta commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +    pointer-events:none;
```suggestion
    pointer-events: none;
```

2020-09-28 03:54 UTC, huy-ta commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +    align-items: center;
```suggestion
    .all-centered;
```

2020-09-28 03:55 UTC, huy-ta commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +  }
```suggestion
    height: 39px;
    
    &:hover{
      cursor: pointer;
    }
  }
```

2020-09-28 03:56 UTC, huy-ta commented on src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
> +
```suggestion
    padding: 0;

    &::-webkit-color-swatch-wrapper {
      padding: 0;
    }

    &::-webkit-color-swatch {
      border: none;
    }
  }  
```

2020-09-28 04:45 UTC, rezk2ll approved these changes

2020-09-28 05:58 UTC, huy-ta requested changes
abc

2020-09-29 01:16 UTC, huy-ta approved these changes

2020-09-29 02:16 UTC, tuanlc approved these changes

2020-09-29 02:21 UTC, merged